"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

// Two-step deletion: the user clicks "Delete account", a confirmation
// panel expands, they type their email exactly, and only then can they
// hit the destructive button. Server also re-validates the email match.
export function DeleteAccountForm({ email }: { email: string }) {
  const router = useRouter();
  const [stage, setStage] = useState<"idle" | "confirming">("idle");
  const [confirmText, setConfirmText] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const matches = confirmText.trim().toLowerCase() === email.toLowerCase();

  async function handleDelete() {
    setSubmitting(true);
    setError(null);
    try {
      const res = await fetch("/api/account/delete", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ confirm: confirmText.trim() }),
      });
      if (!res.ok) {
        const j = (await res.json().catch(() => ({}))) as { error?: string };
        throw new Error(j.error ?? `Request failed (${res.status})`);
      }
      // Sign-out cookie clears on server. Bounce home with a tiny query
      // marker so we could (later) show a "your account was deleted"
      // toast if we wanted to.
      router.push("/?account-deleted=1");
    } catch (err) {
      setSubmitting(false);
      setError(err instanceof Error ? err.message : String(err));
    }
  }

  if (stage === "idle") {
    return (
      <div>
        <h2 className="text-2xl font-light tracking-tight">Danger zone</h2>
        <p className="mt-3 text-sm leading-relaxed text-charcoal/70">
          Deleting your account removes your sign-in, every claim you have
          uploaded, every file stored in your private folder, and every
          report generated by Vvon. This cannot be undone.
        </p>
        <button
          type="button"
          onClick={() => setStage("confirming")}
          className="mt-5 inline-flex items-center gap-2 border border-red-700/60 px-5 py-3 text-sm font-medium uppercase tracking-[0.22em] text-red-800 transition hover:bg-red-700 hover:text-ivory"
        >
          Delete my account
        </button>
      </div>
    );
  }

  return (
    <div>
      <h2 className="text-2xl font-light tracking-tight">Confirm deletion</h2>
      <p className="mt-3 text-sm leading-relaxed text-charcoal/70">
        To confirm, type your account email exactly:{" "}
        <span className="font-medium">{email}</span>
      </p>
      <input
        type="text"
        autoComplete="off"
        value={confirmText}
        onChange={(e) => setConfirmText(e.target.value)}
        placeholder={email}
        className="mt-4 block w-full max-w-md border border-charcoal/20 bg-ivory px-4 py-3 text-base text-charcoal placeholder:text-charcoal/40 focus:border-red-700 focus:outline-none"
      />
      {error && (
        <p role="alert" className="mt-4 text-sm text-red-800">
          {error}
        </p>
      )}
      <div className="mt-5 flex flex-wrap gap-3">
        <button
          type="button"
          disabled={!matches || submitting}
          onClick={handleDelete}
          className="inline-flex items-center gap-2 border border-red-700 bg-red-700 px-6 py-3 text-sm font-medium uppercase tracking-[0.22em] text-ivory transition hover:bg-transparent hover:text-red-800 disabled:cursor-not-allowed disabled:opacity-40"
        >
          {submitting ? "Deleting…" : "Permanently delete"}
        </button>
        <button
          type="button"
          onClick={() => {
            setStage("idle");
            setConfirmText("");
            setError(null);
          }}
          disabled={submitting}
          className="inline-flex items-center gap-2 border border-charcoal/30 px-6 py-3 text-sm font-medium uppercase tracking-[0.22em] text-charcoal transition hover:border-charcoal disabled:opacity-50"
        >
          Cancel
        </button>
      </div>
    </div>
  );
}
